# Generated by Django 3.1.7 on 2021-06-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='feedback_files/'),
        ),
    ]
