# Generated by Django 5.2.5 on 2026-04-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_set_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
