# Generated by Django 4.2.6 on 2023-10-12 12:53

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_auto_20220727_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='no-avatar.png', upload_to=main.models.avatar_upload_path),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
