# Generated by Django 3.1.1 on 2020-09-21 08:38

from django.db import migrations
from django.conf import settings


def set_admin_profile(apps, schema_editor):
    user_obj = apps.get_model("main", "User")
    user_profile_obj = apps.get_model("user_profile", "Profile")
    admin = user_obj.objects.get(email=settings.SUPERUSER_EMAIL)
    user_profile_obj.objects.create(user=admin)


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('main', '0002_set_superuser'),
    ]

    operations = [
        migrations.RunPython(set_admin_profile),
    ]
