# Generated by Django 3.1.1 on 2020-09-21 08:38
import os

from django.db import migrations


def set_admin_profile(apps, schema_editor):
    if email := os.getenv('SUPERUSER_EMAIL'):
        user_obj = apps.get_model("main", "User")
        user_profile_obj = apps.get_model("user_profile", "Profile")
        admin = user_obj.objects.get(email=email)
        user_profile_obj.objects.create(user=admin)


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('main', '0002_set_superuser'),
    ]

    operations = [
        migrations.RunPython(set_admin_profile),
    ]
