# Generated by Django 3.2.11 on 2022-01-07 20:06

import actions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='likedislike',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=actions.models.like_content_limit, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='likedislike',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
