# Generated by Django 4.2.8 on 2024-01-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.CharField(choices=[('update_avatar', 'Update Avatar')], max_length=50),
        ),
    ]
