# Generated by Django 4.2.8 on 2024-01-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('actions', '0002_alter_action_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.CharField(
                choices=[('update_avatar', 'Update Avatar'), ('create_article', 'Create Article')], max_length=50
            ),
        ),
    ]
