# SMTP Server for mail testing

services:
  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - target: 1025
        published: 1025
        protocol: tcp
        mode: host
      - target: 8025
        published: 8025
        protocol: tcp
        mode: host
